In [4]:
import numpy as np
# iniallize 
def sigmoid(inX):  
    return 1.0/(1+np.exp(-inX))  
W1 = np.array([ [-0.20, 0.48, -0.52],
                [-0.56, 1.97,  1.39],
                [ 0.10, 0.28,  0.77],
                [ 1.25, 1.01, -1.30] ] )
b1 = np.array([ [0.27],
                [0.23],
                [1.35],
                [0.89] ])             
W2 = np.array([ [-1.00, -0.19,  0.83, -0.22],
                [-0.27,  0.24,  1.62, -0.51],
                [-0.29,  0.06,  0.15,  0.26],
                [ 0.00,  0.67, -0.36, -0.42]  ])             
b2 = np.array([ [-1.19],
                [-0.93],
                [-0.43],
                [ 0.28]  ])             
W3 = np.array([ [-0.13,  0.01, -0.10,  0.03],
                [-0.24, -0.02, -0.15, -0.10]  ])             
b3 = np.array([ [-0.13],
                [ 0.03]  ])
X = np.array([  [0.13, 0.68, 0.80, 0.57, 0.97],
                [0.63, 0.89, 0.50, 0.35, 0.71],
                [0.50, 0.23, 0.24, 0.79, 0.50]  ])

In [5]:
H1 = sigmoid( np.dot(W1,X) + b1 )
H2 = sigmoid( np.dot(W2,H1) + b2 )
Out = np.dot(W3,H2) + b3

In [6]:
Tabelle = np.hstack(  (H1.T, H2.T, Out.T) )
print("   h1_1   h1_2   h1_3   h1_4    h2_1  h2_2   h2_3   h2_4   o1     o2")
np.set_printoptions(precision=3, suppress=True)
print(Tabelle)

   h1_1   h1_2   h1_3   h1_4    h2_1  h2_2   h2_3   h2_4   o1     o2
[[ 0.571  0.89   0.873  0.739  0.203  0.542  0.445  0.563 -0.179 -0.153]
 [ 0.609  0.872  0.863  0.912  0.19   0.512  0.453  0.543 -0.179 -0.148]
 [ 0.556  0.75   0.853  0.889  0.202  0.507  0.453  0.526 -0.181 -0.149]
 [ 0.478  0.845  0.892  0.717  0.223  0.556  0.451  0.556 -0.182 -0.158]
 [ 0.539  0.856  0.884  0.897  0.205  0.526  0.458  0.539 -0.181 -0.152]]
